Controllers/TableController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RestorantManagement.Helper;
using RestorantManagement.Models;
using RestorantManagement.Services.Interfaces;
using RestorantManagement.ViewModels;
using System.Collections.Generic;
using System.Linq;

namespace RestorantManagement.Controllers
{
    [Authorize]
    public class TableController : Controller
    {
        private readonly ITableService tableService;

        public TableController(ITableService tableService)
        {
            this.tableService = tableService;
        }
        public IActionResult Overview()
        {
            List<Table> tablesDB = tableService.GetAll();
            var tables = tablesDB.Select(x => x.ToTableOverview()).ToList();
            return View(tables);
        }

        public IActionResult TakeTable(int tableId)
        {
            tableService.TakeTable(tableId);
            return RedirectToAction(nameof(Overview));
        }

        public IActionResult Details(int tableId) 
        {
            var table = tableService.GetById(tableId).ToTableDetails();
            return View(table);
        }

        public IActionResult CloseTable(int tableId)
        {
            tableService.Close(tableId);
            return RedirectToAction(nameof(Overview));
        }

        [HttpPost]
        public IActionResult AddToTable([FromBody]AddToTableViewModel model)
        {
            tableService.AddProductsToTable(model.TableId, model.Products);
            return Ok();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestorantManagement</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
   
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Table" asp-action="Overview">RestorantManagement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Table" asp-action="Overview">Home</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>

    <script src="~/js/site.js" asp-append-version="true"></script>
    

    @RenderSection("Scripts", required: false)
</body>
</html>